language: rust

rust:
  - 1.31.0

cache: cargo

script:
  - cargo test --verbose --release -p zero-chain-proofs -p bellman-verifier -p zero-chain-crypto -p jubjub -p zero-chain-pairing -p zero-chain-primitives
