# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: rust

rust:
  - stable
  - nightly

cache: cargo

branches:
  only:
  - master

env:
  - RUST_BACKTRACE=1

matrix:
  include:
    - rust: stable
      env: TARGET=native
    - rust: nightly
      env: TARGET=wasm

before_install:
  - chmod +x ./ci/script.sh
  # Check how much space we've got on this machine.
  - df -h

script:
  - ./ci/script.sh

after_script:
  # Check how much free disk space left after the build
