[package]
name = "sonic"
version = "0.1.0"
authors = ["Osuke Sudo <dish230@gmail.com>"]
edition = "2018"

[dependencies]
pairing = { package = "zero-chain-pairing", path = "../pairing" }
bellman = { git = "https://github.com/zkcrypto/bellman" }