[package]
name = "zero-chain-runtime"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rustc-hex = { version = "1.0", optional = true }
hex-literal = { version = "0.1.0", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
sr-std = { git = "https://github.com/paritytech/substrate", default-features = false }
sr-io = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-support = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-keyring = { git = "https://github.com/paritytech/substrate", optional = true }
srml-balances = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-consensus = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-aura = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-executive = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-indices = { git = "https://github.com/paritytech/substrate", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-system = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-sudo = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-client = { git = "https://github.com/paritytech/substrate", default-features = false }
sr-version = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-consensus-aura-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }

parity-crypto = "0.2.0"
rust-crypto = "0.2.36"
rand = { version = "0.4", default-features = false}
substrate-keystore = { git = "https://github.com/paritytech/substrate" }

byteorder = { version = "1", default-features = false }
# pairing = { git = "https://github.com/sorpaas/pairing", default-features = false }
blake2-rfc = { version = "0.2.18", default-features = false }

zero-chain-proofs = { path = "../proofs" }
sapling-crypto = { git = "https://github.com/osuketh/zcash-to-substrate" }
pairing = { git = "https://github.com/osuketh/zcash-to-substrate" }
zero-chain-crypto = { path = "../crypto" }
zero-chain-primitives = { path = "../primitives" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-executive/std",
	"srml-aura/std",
	"srml-indices/std",
	"sr-primitives/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-sudo/std",
	"sr-version/std",
	"serde_derive",
	"serde/std",
	"safe-mix/std",
	"substrate-consensus-aura-primitives/std",
	"rand/std",	
	"byteorder/std",
	# "pairing/std",
	"blake2-rfc/std",
]
