[package]
name = "zero-chain-runtime"
version = "0.9.0"
authors = ["Osuke <dish230@gmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate", default-features = false }
version = { package = "sr-version", git = "https://github.com/paritytech/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/paritytech/substrate", default-features = false }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
balances = { package = "srml-balances", git = "https://github.com/paritytech/substrate", default-features = false }
consensus = { package = "srml-consensus", git = "https://github.com/paritytech/substrate", default-features = false }
aura = { package = "srml-aura", git = "https://github.com/paritytech/substrate", default-features = false }
executive = { package = "srml-executive", git = "https://github.com/paritytech/substrate", default-features = false }
indices = { package = "srml-indices", git = "https://github.com/paritytech/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/paritytech/substrate", default-features = false }
sudo = { package = "srml-sudo", git = "https://github.com/paritytech/substrate", default-features = false }
runtime-primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
substrate-client = { git = "https://github.com/paritytech/substrate", default-features = false }
consensus-aura = { package = "substrate-consensus-aura-primitives", git = "https://github.com/paritytech/substrate", default-features = false }

parity-crypto = "0.3.0"
rust-crypto = "0.2.36"
rand = { version = "0.4", default-features = false}

pairing = { path = "../pairing", default-features = false }
bellman-verifier = { path = "../bellman-verifier", default-features = false }
zprimitives = { package = "zero-chain-primitives", path = "../primitives" }
jubjub = { path = "../jubjub", default-features = false }

[dependencies.blake2-rfc]
git = "https://github.com/gtank/blake2-rfc"
rev = "7a5b5fc99ae483a0043db7547fb79a6fa44b88a9"
default-features = false

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"parity-codec-derive/std",
	"primitives/std",
	"substrate-client/std",
	"rstd/std",
	"runtime-io/std",
	"support/std",
	"balances/std",
	"executive/std",
	"aura/std",
	"indices/std",
	"primitives/std",
	"system/std",
	"timestamp/std",
	"sudo/std",
	"version/std",
	"serde_derive",
	"serde/std",
	"safe-mix/std",
	"consensus-aura/std",
	"rand/std",		
	"pairing/std",
	"blake2-rfc/std",
	"bellman-verifier/std",
]
