[package]
name = "srml-executive"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
srml-indices = { path = "../indices", default-features = false }
# fees = { package = "srml-fees", path = "../fees" }

[dependencies.serde]
default-features = false
version = '1.0'

[dependencies.parity-codec]
default-features = false
version = '3.1'

[dependencies.parity-codec-derive]
default-features = false
version = '3.1'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = '9112a28af677b75cd6f935dda34d283bb4f676e7'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = '9112a28af677b75cd6f935dda34d283bb4f676e7'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = '9112a28af677b75cd6f935dda34d283bb4f676e7'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-support'
rev = '9112a28af677b75cd6f935dda34d283bb4f676e7'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = '9112a28af677b75cd6f935dda34d283bb4f676e7'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '9112a28af677b75cd6f935dda34d283bb4f676e7'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-balances'
rev = '9112a28af677b75cd6f935dda34d283bb4f676e7'

[features]
default = ["std"]
std = [
	"rstd/std",
	"support/std",
	"serde/std",
	"parity-codec/std",
	'parity-codec-derive/std',
	"primitives/std",	
	"system/std",
	"runtime-primitives/std",	
	'runtime-io/std',
	"balances/std",
]
