[profile.release]
lto = true
panic = 'abort'

[lib]
crate-type = ['cdylib']
[dependencies.zero-chain-runtime]
default-features = false
path = '..'

[features]
default = []
std = ['zero-chain-runtime/std']

[package]
authors = ['Osuke Sudo <dish230@gmail.com>']
edition = '2018'
name = 'zero-chain-runtime-wasm'
version = '0.9.0'

[workspace]
members = []
