[profile.release]
lto = true
panic = 'abort'

[lib]
crate-type = ['cdylib']
[dependencies.zerochain-runtime]
default-features = false
path = '..'

[features]
default = []
std = ['zerochain-runtime/std']

[package]
authors = ['Osuke Sudo <dish230@gmail.com>']
edition = '2018'
name = 'zerochain-runtime-wasm'
version = '0.9.0'

[workspace]
members = []
