[package]
name = "zero-chain-proofs"
version = "0.1.0"
authors = ["osuke <dish230@gmail.com>"]

[dependencies]
# pairing = { git = "https://github.com/zcash/librustzcash" }
# bellman = { git = "https://github.com/zcash/librustzcash" }
# sapling-crypto = { git = "https://github.com/zcash/librustzcash" }
pairing = { git = "https://github.com/osuketh/zcash-to-substrate" }
bellman = { git = "https://github.com/osuketh/zcash-to-substrate" }
sapling-crypto = { git = "https://github.com/osuketh/zcash-to-substrate" }

rand = { version = "0.4", default-features = false}
byteorder = { version = "1", default-features = false }
zero-chain-crypto = { path = "../crypto"}
parity-codec-derive = { version = "3.0" }
parity-codec = { version = "3.0", default-features = false }
serde = { version = "1.0", optional = true, default-features = false }
serde_derive = { version = "1.0", optional = true }

[dependencies.blake2-rfc]
git = "https://github.com/gtank/blake2-rfc"
rev = "7a5b5fc99ae483a0043db7547fb79a6fa44b88a9"

[feature]
default = ["std"]
std = [
    "pairing/std",
    "rand/std",
    "byteorder/std",
]
