[package]
name = "proofs"
version = "0.1.0"
authors = ["osuke <dish230@gmail.com>"]

[dependencies]
bellman = { git = "https://github.com/osuketh/bellman", branch = "wasm" }
pairing = { git = "https://github.com/sorpaas/pairing", default-features = false }
rand = { version = "0.4", default-features = false}
byteorder = { version = "1", default-features = false }
sapling-crypto = { git = "https://github.com/zcash/librustzcash" }

[feature]
default = ["std"]
std = [
    "pairing/std",
    "rand/std",
    "byteorder/std",
]
